In [223]:
import tensorflow as tf

In [224]:
from sklearn import model_selection

In [225]:
from sklearn.preprocessing import MinMaxScaler

In [226]:
import pandas as pd
df = pd.read_csv('CHD.csv', sep=',')
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [227]:
split_train, split_test = model_selection.train_test_split(df, test_size=0.3)

In [228]:
scaler = MinMaxScaler()

In [229]:
test_xs = split_test.loc[:, 'HouseAge':'Longitude']
train_xs = split_train.loc[:, 'HouseAge':'Longitude']

In [230]:
test_y = split_test['medianHouseValue']
train_y = split_train['medianHouseValue']

In [231]:
train_fit = scaler.fit(train_xs)

In [232]:
trans_train = scaler.transform(test_xs)
trans_test = scaler.transform(train_xs)

In [233]:
age = tf.feature_column.numeric_column('HouseAge')
rooms = tf.feature_column.numeric_column('AveRooms')
bedrooms = tf.feature_column.numeric_column('AveBedrms')
population = tf.feature_column.numeric_column('Population')
occup = tf.feature_column.numeric_column('AveOccup')
income = tf.feature_column.numeric_column('MedInc')

In [234]:
features = [age, rooms, bedrooms, population, occup, income]

In [235]:
input_f = tf.estimator.inputs.pandas_input_fn(x=train_xs, y=train_y, batch_size=200, num_epochs = 10, shuffle=True)

In [333]:
estim = tf.estimator.DNNRegressor(feature_columns=features, hidden_units=[2,3,4,5,6,5,4,3,2])

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\134E~1\\AppData\\Local\\Temp\\tmpxfkrlzbv', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000008DB33EB940>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [334]:
estim.train(input_fn=input_f, steps=1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\134E~1\AppData\Local\Temp\tmpxfkrlzbv\model.ckpt.
INFO:tensorflow:loss = 857.95337, step = 1
INFO:tensorflow:global_step/sec: 196.684
INFO:tensorflow:loss = 405.5618, step = 101 (0.508 sec)
INFO:tensorflow:global_step/sec: 243.414
INFO:tensorflow:loss = 440.54236, step = 201 (0.411 sec)
INFO:tensorflow:global_step/sec: 249.478
INFO:tensorflow:loss = 437.3486, step = 301 (0.401 sec)
INFO:tensorflow:global_step/sec: 250.978
INFO:tensorflow:loss = 306.39905, step = 401 (0.398 sec)
INFO:tensorflow:global_step/sec: 249.109
INFO:tensorflow:loss = 328.54193, step = 501 (0.401 sec)
INFO:tensorflow:global_step/sec: 249.094
INFO:tensorflow:loss = 364.44238, step = 601 (0.401 sec)
INFO:tensorflow:global_step/s

In [335]:
predict_f = tf.estimator.inputs.pandas_input_fn(x=test_xs, batch_size=10, num_epochs = 1, shuffle=True)
predictions = estim.predict(input_fn=predict_f)

In [336]:
predictions= list(predictions)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\134E~1\AppData\Local\Temp\tmpxfkrlzbv\model.ckpt-723
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [337]:
preds = [i['predictions'] for i in predictions]

In [338]:
preds

[array([1.589514], dtype=float32),
 array([1.4644406], dtype=float32),
 array([1.5451515], dtype=float32),
 array([3.23269], dtype=float32),
 array([1.7914503], dtype=float32),
 array([1.6234801], dtype=float32),
 array([1.7501614], dtype=float32),
 array([1.7774179], dtype=float32),
 array([1.6108372], dtype=float32),
 array([1.4589696], dtype=float32),
 array([1.5650864], dtype=float32),
 array([1.5779881], dtype=float32),
 array([1.5615673], dtype=float32),
 array([1.8325527], dtype=float32),
 array([2.104192], dtype=float32),
 array([1.6237314], dtype=float32),
 array([1.5798192], dtype=float32),
 array([1.6722548], dtype=float32),
 array([1.8329594], dtype=float32),
 array([1.6057589], dtype=float32),
 array([1.7683074], dtype=float32),
 array([1.5840304], dtype=float32),
 array([2.0118687], dtype=float32),
 array([1.6643398], dtype=float32),
 array([1.6726534], dtype=float32),
 array([1.7825377], dtype=float32),
 array([1.4866862], dtype=float32),
 array([1.5450623], dtype=float3

In [339]:
from sklearn import metrics

metrics.mean_squared_error(preds, test_y)**0.5

1.2375981474627693