# Regression Exercise 

California Housing Data

This data set contains information about all the block groups in California from the 1990 Census. In this sample a block group on average includes 1425.5 individuals living in a geographically compact area. 

The task is to aproximate the median house value of each block from the values of the rest of the variables. 

 It has been obtained from the LIACC repository. The original page where the data set can be found is: http://www.liaad.up.pt/~ltorgo/Regression/DataSets.html.
 

The Features:
 
* housingMedianAge: continuous. 
* totalRooms: continuous. 
* totalBedrooms: continuous. 
* population: continuous. 
* households: continuous. 
* medianIncome: continuous. 
* medianHouseValue: continuous. 

## The Data

** Import the cal_housing_clean.csv file with pandas. Separate it into a training (70%) and testing set(30%).**

In [142]:
import pandas as pd

In [143]:
CaliforniaHousing = pd.read_csv("California Housing Data.csv", sep=",")
CaliforniaHousing.head()

Longitude  Latitude  HousingMedianAge  TotalRooms  TotalBedrooms  \
0    -122.23     37.88              41.0       880.0          129.0   
1    -122.22     37.86              21.0      7099.0         1106.0   
2    -122.24     37.85              52.0      1467.0          190.0   
3    -122.25     37.85              52.0      1274.0          235.0   
4    -122.25     37.85              52.0      1627.0          280.0   

   Population  Households  MedianIncome  MedianHouseValue  
0       322.0       126.0        8.3252          452600.0  
1      2401.0      1138.0        8.3014          358500.0  
2       496.0       177.0        7.2574          352100.0  
3       558.0       219.0        5.6431          341300.0  
4       565.0       259.0        3.8462          342200.0

In [144]:
CaliforniaHousing.describe()

Longitude      Latitude  HousingMedianAge    TotalRooms  \
count  20640.000000  20640.000000      20640.000000  20640.000000   
mean    -119.569704     35.631861         28.639486   2635.763081   
std        2.003532      2.135952         12.585558   2181.615252   
min     -124.350000     32.540000          1.000000      2.000000   
25%     -121.800000     33.930000         18.000000   1447.750000   
50%     -118.490000     34.260000         29.000000   2127.000000   
75%     -118.010000     37.710000         37.000000   3148.000000   
max     -114.310000     41.950000         52.000000  39320.000000   

       TotalBedrooms    Population    Households  MedianIncome  \
count   20640.000000  20640.000000  20640.000000  20640.000000   
mean      537.898014   1425.476744    499.539680      3.870671   
std       421.247906   1132.462122    382.329753      1.899822   
min         1.000000      3.000000      1.000000      0.499900   
25%       295.000000    787.000000    280.000000      2.563400   
50%       435.000000   1166.000000    409.000000      3.534800   
75%       647.000000   1725.000000    605.000000      4.743250   
max      6445.000000  35682.000000   6082.000000     15.000100   

       MedianHouseValue  
count      20640.000000  
mean      206855.816909  
std       115395.615874  
min        14999.000000  
25%       119600.000000  
50%       179700.000000  
75%       264725.000000  
max       500001.000000

In [145]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(CaliforniaHousing, test_size=0.3)

X_train, y_train, X_test, y_test = train_set.iloc[:,:-1], train_set.iloc[:,-1], test_set.iloc[:,:-1], test_set.iloc[:,-1]

In [146]:
print('train:', len(X_train), '-', len(X_train)/len(CaliforniaHousing)*100, '%')
print('test:', len(X_test), '-', len(X_test)/len(CaliforniaHousing)*100, '%')

train: 14448 - 70.0 %
test: 6192 - 30.0 %


### Scale the Feature Data

** Use sklearn preprocessing to create a MinMaxScaler for the feature data. Fit this scaler only to the training data. Then use it to transform X_test and X_train. Then use the scaled X_test and X_train along with pd.Dataframe to re-create two dataframes of scaled data.**

In [147]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [148]:
X_train_scaled = scaler.transform(X_train)
print(X_train_scaled)

[[0.63479145 0.13617021 0.31372549 ... 0.03108271 0.08222332 0.23112095]
 [0.75076297 0.03297872 0.19607843 ... 0.04117268 0.08156553 0.12892236]
 [0.63784334 0.14468085 0.66666667 ... 0.04871213 0.06528531 0.25818954]
 ...
 [0.22278739 0.5787234  0.17647059 ... 0.03635192 0.08321    0.26810665]
 [0.4069176  0.50957447 0.62745098 ... 0.01549931 0.02861371 0.13301196]
 [0.61953204 0.15       0.82352941 ... 0.04447995 0.07778326 0.12580516]]


In [149]:
X_test_scaled = scaler.transform(X_test)
print(X_test_scaled)

[[0.45676501 0.45       1.         ... 0.02343115 0.06018747 0.21360395]
 [0.28179044 0.69255319 0.37254902 ... 0.00854845 0.01858247 0.19325251]
 [0.67141404 0.16170213 0.62745098 ... 0.03708064 0.04966288 0.22737617]
 ...
 [0.62360122 0.12978723 0.8627451  ... 0.02926091 0.09505016 0.18034234]
 [0.60732452 0.14680851 0.70588235 ... 0.09893775 0.17003782 0.19215597]
 [0.61241099 0.15212766 0.74509804 ... 0.0372488  0.05426739 0.10044689]]


In [150]:
X_train_data = pd.DataFrame(data=X_train_scaled, columns=X_train.columns, index=X_train.index)
X_train.head()

Longitude  Latitude  HousingMedianAge  TotalRooms  TotalBedrooms  \
11642    -118.06     33.83              17.0      1973.0          516.0   
15131    -116.92     32.86              11.0      2204.0          518.0   
7123     -118.03     33.91              35.0      2323.0          406.0   
7624     -118.26     33.85              24.0      9071.0         1335.0   
9553     -120.64     37.38              21.0      3157.0          637.0   

       Population  Households  MedianIncome  
11642      1112.0       501.0        3.8512  
15131      1472.0       497.0        2.3693  
7123       1741.0       398.0        4.2437  
7624       4558.0      1327.0        5.5420  
9553       2268.0       620.0        2.5670

In [151]:
X_test_data = pd.DataFrame(data=X_test_scaled, columns=X_train.columns, index=X_test.index)
X_test.head()

Longitude  Latitude  HousingMedianAge  TotalRooms  TotalBedrooms  \
2157     -119.81     36.78              52.0      2281.0          371.0   
20617    -121.53     39.06              20.0       561.0          109.0   
13197    -117.70     34.07              33.0      1552.0          288.0   
12106    -117.34     33.98              10.0     17286.0         4952.0   
16442    -121.29     38.14              34.0      1500.0          337.0   

       Population  Households  MedianIncome  
2157        839.0       367.0        3.5972  
20617       308.0       114.0        3.3021  
13197      1326.0       303.0        3.7969  
12106      9851.0      4616.0        1.7579  
16442       674.0       282.0        2.5150

### Create Feature Columns

** Create the necessary tf.feature_column objects for the estimator. They should all be trated as continuous numeric_columns. **

In [152]:
import tensorflow as tf

In [153]:
X_train.columns

Index(['Longitude', 'Latitude', 'HousingMedianAge', 'TotalRooms',
       'TotalBedrooms', 'Population', 'Households', 'MedianIncome'],
      dtype='object')

In [154]:
feat_cols = [tf.feature_column.numeric_column(i, shape=[1]) for i in X_train.columns]
feat_cols

[_NumericColumn(key='Longitude', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='Latitude', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='HousingMedianAge', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='TotalRooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='TotalBedrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='Population', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='Households', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='MedianIncome', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

** Create the input function for the estimator object. (play around with batch_size and num_epochs)**

In [155]:
input_func = tf.estimator.inputs.pandas_input_fn(x = X_train_data, y = y_train, batch_size = 10, num_epochs = 1000, shuffle=True)

** Create the estimator model. Use a DNNRegressor. Play around with the hidden units! **

In [156]:
estimator = tf.estimator.DNNRegressor(feature_columns = feat_cols, hidden_units = [6,10,15,10,6])

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\valer\\AppData\\Local\\Temp\\tmpneqo265l', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000025F60471C18>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


##### ** Train the model for ~1,000 steps. (Later come back to this and train it for more and check for improvement) **

In [157]:
estimator.train(input_fn = input_func, steps=1000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\valer\AppData\Local\Temp\tmpneqo265l\model.ckpt.
INFO:tensorflow:loss = 555659800000.0, step = 1
INFO:tensorflow:global_step/sec: 302.026
INFO:tensorflow:loss = 147446020000.0, step = 101 (0.336 sec)
INFO:tensorflow:global_step/sec: 412.623
INFO:tensorflow:loss = 255753850000.0, step = 201 (0.238 sec)
INFO:tensorflow:global_step/sec: 468.538
INFO:tensorflow:loss = 67197950000.0, step = 301 (0.213 sec)
INFO:tensorflow:global_step/sec: 468.504
INFO:tensorflow:loss = 85235780000.0, step = 401 (0.213 sec)
INFO:tensorflow:global_step/sec: 486.777
INFO:tensorflow:loss = 65639170000.0, step = 501 (0.204 sec)
INFO:tensorflow:global_step/sec: 462.056
INFO:tensorflow:loss = 48549290000.0, step = 601 (0.216 se

** Create a prediction input function and then use the .predict method off your estimator model to create a list or predictions on your test data. **

In [158]:
predict_input_func = tf.estimator.inputs.pandas_input_fn(x=X_test_data, batch_size=10,num_epochs=1,shuffle=False)

In [159]:
predicts = estimator.predict(input_fn=predict_input_func)

In [160]:
final=[i['predictions'] for i in list(predicts)]

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\valer\AppData\Local\Temp\tmpneqo265l\model.ckpt-1000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


** Calculate the RMSE. You should be able to get around 100,000 RMSE (remember that this is in the same units as the label.) Do this manually or use [sklearn.metrics](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html) **

In [161]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test,final_predicts)**0.5
rmse

122566.47572429282

# Great Job!